FLAMEGPU/FLAMEGPU2-docs

src/guide/3-behaviour-definition/1-defining-functions.rst, src/guide/3-behaviour-definition/4-agent-communication.rst, src/guide/4-initial-conditions/5-from-disk.rst, src/guide/5-running-a-sim/2-launching-a-sim.rst, src/guide/5-running-a-sim/3-end-conditions.rst, src/guide/7-submodels/1-defining-a-submodel.rst, src/guide/8-running-multiple-sims/4-multiple-sims.rst, src/index.rst
Add agent functions, messages, launching sim, end conditions, submodels, ensembles
=> Add agent functions, messages, launching sim, end conditions, submodels, ensembles

src/guide/3-behaviour-definition/4-agent-communication.rst
Adds several missing details, including everything about array messaging.
Closes #31
=> Update agent communication section.

src/guide/3-behaviour-definition/4-agent-communication.rst
=> Initial MessageBucket docs

src/guide/11-flamegpu2-source/1-build-from-source.rst, src/guide/3-behaviour-definition/6-host-functions.rst, src/guide/9-visualisation/1-building-with-vis.rst, src/guide/9-visualisation/2-setting-up-vis.rst, src/guide/9-visualisation/3-visualising-agents.rst, src/guide/9-visualisation/4-adding-details.rst, src/guide/9-visualisation/5-visualisation-controls.rst, src/guide/9-visualisation/index.rst
This is a draft PR containing removed contents of the Visualisation section from the userguide.
They need completing prior to merging. 
+ Re-add empty/template visualisation pages. This needs completing prior to re-merging.
Once complete this will close #49
=> Visualisation Userguide

CMakeLists.txt, src/guide/2-model-definition/2-environment.rst
Syntax was wrong for some reason.
=> Correct EnvironmentDescription guide.

src/guide/5-running-a-sim/4-collecting-data.rst, src/guide/7-submodels/1-defining-a-submodel.rst, src/guide/7-submodels/index.rst, src/guide/8-running-multiple-sims/4-multiple-sims.rst, src/guide/8-running-multiple-sims/index.rst
Ended up doing a major rework for 2 pages, I think both are good to go. Have compiled locally and can't see any syntax issues breaking the pages.
=> CUDASimulation logging guide

src/guide/2-model-definition/1-model.rst, src/guide/2-model-definition/2-environment.rst, src/guide/2-model-definition/3-agent.rst, src/guide/2-model-definition/index.rst, src/guide/3-behaviour-definition/1-defining-agent-functions.rst, src/guide/3-behaviour-definition/2-modifying-agent-variables.rst, src/guide/3-behaviour-definition/3-interacting-with-environment.rst, src/guide/3-behaviour-definition/4-agent-communication.rst, src/guide/3-behaviour-definition/5-conditional-behaviours.rst, src/guide/3-behaviour-definition/6-host-functions.rst, src/guide/6-agent-birth-death/1-agent-birth-device.rst, src/guide/6-agent-birth-death/3-agent-death.rst
Primarily when through adding cross references to API docs.
Have tested these changes multiple times locally, and think I've caught all the issues.
I need to go through these further, however want to merge this before the meeting this afternoon
Closes #66
=> Various fixes

.github/workflows/build.yml
This just avoids having nested zips both named username.zip which may be confusing
=> Minor change to archive name

src/guide/6-agent-birth-death/1-agent-birth-device.rst
Closes https://github.com/FLAMEGPU/FLAMEGPU2/issues/795
=> Remove wrong info regarding device agent birth

src/guide/running-a-simulation/configuring-execution.rst, src/guide/running-multiple-simulations/index.rst
Pairs with https://github.com/FLAMEGPU/FLAMEGPU2/pull/865
=> CUDASimulation config can now have user defined defaults.

.github/workflows/build.yml, .github/workflows/publish.yml, readme.md, requirements.txt
+ [x] Adds multiple python versions to CI
+ [x] Updates package dependencies to fix recent python versions
+ [x] Updates version spec in readme
Closes #95
=> Support in different Python versions

src/guide/visualisation/visualising-agents.rst
Added 2 new models and descriptions for triangular pyramids.
related to this FLAMEGPU-visualiser PR: https://github.com/FLAMEGPU/FLAMEGPU2-visualiser/pull/91
=> Added models and descriptions for 4-poly triangular pyramids to visualisation documentation.

CMakeLists.txt
=> BugFix: Could not trigger CMake gen with BUILD_API_DOCUMENTATION=OFF

CMakeLists.txt
Probably should have actually tested that last fix before merge, it was still trying to run Exhale.
=> Bugfix: Attempt 2.

src/guide/visualisation/visualising-agents.rst
Also removed semicolons from alot of Python code examples on same page.
Page includes an embed of [this](https://youtu.be/7Rm5n5yDDg4) video.
See main repo PR for details: https://github.com/FLAMEGPU/FLAMEGPU2/pull/904
=> Document keyframe animated agent models.

.github/problem-matchers.json, .github/workflows/build.yml, CMakeLists.txt, src/guide/visualisation/visualising-agents.rst, src/tutorial/index.rst
+ [x] Adds new CI builds
+ Python 3.7, No API docs, Errors on first warning
+ Python 3.7, No API docs, Emits and annotates warnings
+ [x] Fix existing sphinx warnings so CI passes
Closes #18 
Closes #106
e.g. (though I'm going to have changed job names since this screenshot)
=> Werror CI build(s)

src/guide/agent-functions/conditional-behaviours.rst
Simple update top reflect addition of agent function conditions in native Python format.
=> Updated docs for agent function conditions

src/guide/agent-functions/agent-communication.rst, src/tutorial/index.rst
Definitely want someone to read these changes, they feel a bit rough to me, not sure if there's a better way to present them.
Relates: https://github.com/FLAMEGPU/FLAMEGPU2/pull/794
=> Docs update for wrapped spatial message iterator.

src/guide/visualisation/visualising-agents.rst
=> Minor change to keyframe examples

src/guide/running-multiple-simulations/index.rst
See: https://github.com/FLAMEGPU/FLAMEGPU2/pull/930
=> Add details of CUDAEnsemble standby blocking.

src/guide/running-a-simulation/configuring-execution.rst, src/guide/running-multiple-simulations/index.rst
Small change for PR [#967](https://github.com/FLAMEGPU/FLAMEGPU2/pull/967)
=> Silence option for unknown args

src/guide/running-multiple-simulations/index.rst
Relates to main lib PR: https://github.com/FLAMEGPU/FLAMEGPU2/pull/983
=> Rename RunPlanVector::setPropertyUniformDistribution() to setPropertyLerp()

src/guide/agent-functions/defining-agent-functions.rst
Relates https://github.com/FLAMEGPU/FLAMEGPU2/pull/999
=> Add details regarding JitifyCache

CMakeLists.txt, src/guide/index.rst, src/guide/telemetry/index.rst
Documentation to match #https://github.com/FLAMEGPU/FLAMEGPU2/pull/987
=> Added telemetry documentation

src/tutorial/index.rst
Spotted by my dissertation student Erald
It appears this resulted from the vis snippet duplicating the run sim code, and Paul constructing the full code by joining all the snippets.
=> BugFix: Native Python Tutorial Code init/ran simulation twice.

src/guide/visualisation/setting-up-vis.rst, src/guide/visualisation/visualisation-controls.rst, src/guide/visualisation/visualising-agents.rst, src/tutorial/index.rst
3 distinct improvements. (Haven't actually done a test build to check they're valid syntax though)
Closes #138 
Closes https://github.com/FLAMEGPU/FLAMEGPU2/issues/1047
=> 3x Vis Related Improvements

src/guide/defining-execution-order/layers.rst
Inspired by: https://github.com/FLAMEGPU/FLAMEGPU2/discussions/1072
=> Clarify available options for adding agent functions to layers.

src/guide/agent-functions/agent-communication.rst
Closes #142
Also unified some of the indentation, and removed some trailing spaces I found.
=> Docs: Accessing array index during array message iteration.

src/index.rst.in
=> Reorder Tutorial to end of sidebar.

src/guide/host-functions/miscellaneous.rst
Added to main lib here: https://github.com/FLAMEGPU/FLAMEGPU2/pull/1082
=> Doc new hostapi misc

src/guide/running-a-simulation/collecting-data.rst, src/guide/running-multiple-simulations/index.rst
Identified during: https://github.com/FLAMEGPU/FLAMEGPU2/discussions/1091#discussioncomment-6480180
Relates: https://github.com/FLAMEGPU/FLAMEGPU2/issues/907
=> Improve clarity of docs for logging agents with states

requirements.txt, src/guide/host-functions/interacting-with-environment.rst, src/guide/running-a-simulation/initial-state.rst
Relates https://github.com/FLAMEGPU/FLAMEGPU2/pull/1087
=> Add details about env MacroProperty IO

src/guide/host-functions/agent-operations.rst
=> BugFix: Order parameter was incorrect for python agent sort example.

src/guide/agent-functions/interacting-with-environment.rst, src/guide/environment/index.rst, src/guide/host-functions/interacting-with-environment.rst, src/guide/running-a-simulation/collecting-data.rst, src/guide/running-a-simulation/initial-state.rst
Relates: https://github.com/FLAMEGPU/FLAMEGPU2/pull/1089
=> Environment Directed Graph

src/guide/visualisation/adding-details.rst, src/guide/visualisation/setting-up-vis.rst, src/guide/visualisation/visualising-agents.rst
See https://github.com/FLAMEGPU/FLAMEGPU2/pull/1239
=> Document graph visualisation additions

src/guide/visualisation/adding-details.rst
Thanks to David Fletcher for spotting this.
=> CodeFix: Variable name changed during example. 

src/guide/defining-agents/index.rst
The representation of ID not set was not discussed.
=> Add detail to Agent IDs

.github/workflows/build.yml, .github/workflows/publish.yml, readme.md, requirements.txt
Also updates min Python used in CI to 3.10 (as 3.9 goes EoL soon)
=> Fix CI by upgrading runs-on and pinned package verisons

.github/workflows/build.yml, .github/workflows/publish.yml, readme.md, requirements.txt, src/quickstart/index.rst, src/tutorial/index.rst
Update docs to reflect updated CUDA 12 & 13 support and C++20 requirement
Includes documenting the wheelhouse for python installation and a few other missed updates
Should be merged at the same time as https://github.com/FLAMEGPU/FLAMEGPU2/pull/1302
=> CUDA 13 and C++20 - 
