.github/workflows/build.yml
.github/workflows/publish.yml

CI build and publish jobs now include the API docs (via the main FLAMEGPU/FLAMEGPU2 repository)
Also adds manually invokeable CI triggers (workflow dispatch).

Add api docs to build workflow

---

.github/workflows/build.yml
.github/workflows/publish.yml
.gitignore
CMakeLists.txt
cmake/FindGraphviz.cmake
readme.md

Cmake fill fail to configure if graphviz (`dot`) cannot be found.
It should now be installed on CI

Add graphviz (dot) as a required dependency

---

src/guide/9-visualisation/index.rst
src/index.rst
src/quickstart/index.rst

This reintroduces the temporarily removed, incomplete quickstart guide. 
This needs completing, and then it can be merged back in to the online documentation. 
It will eventually close #12.

Quickstart Guide

---

.github/workflows/build.yml
.github/workflows/publish.yml

Uploads the built documentation as an artifact on PR updates.
Artifacts are kept for 14 days. 
Includes changes to CI workflows to standardise workflows a little and use the updated repository name

Adjust build workflow to upload the docs as an artifact on PR events

---

src/guide/5-running-a-sim/5-configuring-execution.rst

There should be a table after the first paragraph here: https://docs.flamegpu.com/guide/5-running-a-sim/5-configuring-execution.html
There isn't.
This PR fixes it:

This table had some misaligned columns, so was missing from the website.

---

src/guide/running-multiple-simulations/index.rst

Primarily due to Py complexity setting `error_level` and `devices`.
Also noticed the type for the Py bool.

Improve CUDAEnsemble::EnsembleConfig setting via code examples.

---

src/guide/environment/index.rst
src/guide/running-multiple-simulations/index.rst

Noticed there wasn't actually an example of `RunPlan`/`RunPlanVector`, so added one.
Haven't tested the code examples (because they're incomplete), but they match the updated test cases which were tested.
See https://github.com/FLAMEGPU/FLAMEGPU2/pull/859

Update docs for Py API breaking changes.

---

src/guide/agent-functions/interacting-with-environment.rst
src/guide/host-functions/interacting-with-environment.rst

Two Changes:
* Fix a dead link in host environment
* Add a warning to host and device macro properties, that they won't work if passed directly to `printf()`. This caught out Carlos and I out, I forgot that they wouldn't work when I first tried to debug his code (where he was printing them and they were coming out 0). Very easy mistake to make.

Bugfix 2022 06 16

---

src/guide/agent-functions/conditional-behaviours.rst
src/guide/agent-functions/defining-agent-functions.rst
src/guide/defining-agents/index.rst
src/guide/defining-messages-communication/index.rst
src/guide/flamegpu2-source/contribute.rst
src/guide/host-functions/defining-host-functions.rst
src/guide/host-functions/index.rst

This meant they weren't appearing in the generated HTML.
Have searched all similar tags, and think this catches all at fault.

BugFix: Various Note/Warning boxes were incorrectly defined.

---

src/tutorial/index.rst

This is due to use of a ref inside italisciesed text (invalid rst)
Closes #96

Fix broken reference in tutorial on CMake configuration

---

CMakeLists.txt
src/conf.py.in
src/index.rst.in

Closes #5
CMake requires an explicit list of src/ files to be copied into build. This does not include .in files which are manually configured.
Copies src into build/src, configures .in files into build/src too
exhale/breathe builds into build/src/api rather than src/api
runs sphinx from build/src, producing userguide into the same location build/userguide
allows the same build directory to be used for BUILD_API_DOCUMENTATION=OFF after being used to generate the api docs, but it won't include the api docs in the generated output.
Also possible to now have multiple build directories, with BUILD_API_DOCUMENTAION on/off that do not conflict with one another.
---
This probably won't conflict with active branches, but post-merge the output may be incorrect if files have been created / deleted …

Create api docs inside the build dir, not src

---

src/guide/agent-functions/agent-birth-death.rst
src/guide/agent-functions/agent-communication.rst
src/guide/agent-functions/conditional-behaviours.rst
src/guide/agent-functions/defining-agent-functions.rst
src/guide/agent-functions/index.rst
src/guide/agent-functions/interacting-with-environment.rst
src/guide/agent-functions/modifying-agent-variables.rst
src/guide/agent-functions/random-numbers.rst
src/guide/defining-messages-communication/index.rst
src/tutorial/index.rst

Adds device side examples for all current CUDA C++. Discussion required about naming of this. I personally don't like CUDA C++ as it implies a user might need to know CUDA. The abstraction is to specifically avoid this so it might be better to use "Agent Function/Device C++" and provide some context as to the fact that this is a subset of C++ supported by CUDA in the docs. Pure Python has also been used to describe the Python device side code. This could potentially also be changed.
Main repo PR: https://github.com/FLAMEGPU/FLAMEGPU2/pull/882

Documentation for pure Python device interface

---

.github/workflows/build.yml
.github/workflows/publish.yml

Should close #115 (hopefully). 
It won't fix the warnings on the github pages deployment jobs which we have no control over.

Update 3rd party github actions to fix GHA node deprecation warnings.

---

src/guide/running-a-simulation/configuring-execution.rst
src/guide/running-a-simulation/initial-state.rst
src/guide/running-multiple-simulations/index.rst

Clarified consistent use of verbose and quiet in Ensemble and Simulation. Also updated any examples using verbose/quiet.

Updated verbosity docs

---

src/guide/debugging-models/logging.rst
src/guide/defining-execution-order/exit-conditions.rst
src/guide/defining-execution-order/layers.rst
src/guide/defining-execution-order/submodels.rst
src/guide/host-functions/defining-host-functions.rst
src/tutorial/index.rst

This should now be called automatically.
I think I have removed all usages of `__disown__()` from the docs, checked using `grep -rnw "src/" -e "disown"`.
Relates:
* Issue: https://github.com/FLAMEGPU/FLAMEGPU2/issues/498
* PR: https://github.com/FLAMEGPU/FLAMEGPU2/pull/975

Remove references to __disown__()

---

src/guide/creating-a-model/index.rst
src/guide/debugging-models/logging.rst
src/guide/defining-execution-order/dependency-graph.rst
src/guide/defining-execution-order/exit-conditions.rst
src/guide/defining-execution-order/layers.rst
src/guide/defining-execution-order/submodels.rst
src/guide/host-functions/agent-operations.rst
src/guide/host-functions/defining-host-functions.rst
src/guide/host-functions/interacting-with-environment.rst
src/guide/host-functions/random-numbers.rst
src/tutorial/index.rst

Relates https://github.com/FLAMEGPU/FLAMEGPU2/pull/997

Remove 'Callback' from Python host fn method/class names.

---

src/guide/defining-messages-communication/index.rst

Closes #125
@ptheywood I didn't bother mentioning `getPersistent()`. Most of the getters on the description hierarchy are redundant as 99% of users won't be doing weird dynamic model creation/probing.

Add information regarding message persistence.

---

.github/workflows/build.yml
CMakeLists.txt
cmake/FindFLAMEGPU.cmake
cmake/FindGraphviz.cmake
cmake/FindSphinx.cmake
readme.md
src/guide/agent-functions/agent-birth-death.rst
src/guide/agent-functions/agent-communication.rst
src/guide/agent-functions/interacting-with-environment.rst
src/guide/debugging-models/seatbelts.rst
src/guide/debugging-models/using-a-debugger.rst
src/guide/defining-messages-communication/index.rst
src/guide/flamegpu2-source/contribute.rst
src/guide/performance-troubleshooting/index.rst
src/guide/visualisation/building-with-vis.rst
src/guide/visualisation/setting-up-vis.rst
src/quickstart/index.rst
src/tutorial/index.rst

Changes required due to https://github.com/FLAMEGPU/FLAMEGPU2/pull/991.
Includes prefixing CMake options with `FLAMEGPU_`, use of renamed cmake functions (prefixed `flamegpu_`), prefixed compiler definitions with `FLAMEGPU_` and the change to use `CMAKE_CUDA_ARCHITECTURES` in place of `CUDA_ARCH`.
Now that https://github.com/FLAMEGPU/FLAMEGPU2/pull/991 has been merged, and this repository is only concerned with current master, any CI jobs (or local builds which fetch the main repository) will fail. until this PR is merged.

CMake option/cache prefix changes

---

src/guide/agent-functions/defining-agent-functions.rst

Closes #80
Noticed the comment in the original PR, mentioned selection is based on compiler rather than OS. So I did check whether there was a C++ STL function for the OS specific path delimiter (`:`, `;`), but it doesn't appear so (I did find Java and NodeJS). Not helped by the confusion between delimiter/separator, with most results talking about `/` vs `\`.

Docs: RTC include path

---

src/guide/agent-functions/defining-agent-functions.rst
src/guide/creating-a-model/index.rst
src/guide/defining-agents/index.rst
src/guide/environment/index.rst

I'm not the biggest fan of the location of this new section, but it feels like it needs to be really early, e.g. before environment/agent properties/variables.
*Found out that RST supports footnotes which is cool.*
Closes #51

Add section about supported types to first chapter

---

src/tutorial/index.rst

Update tutorial examples where `addRoot()` has been renamed in FGPU2 to `addExecutionRoot()`, some appear to have previously been missed.

BugFix: Tutorial replace addRoot() with addExecutionRoot()

---

src/guide/defining-messages-communication/index.rst

Cross references agent communication - sending messages.
Closes #100

Add note about optional message output to defining messages chapter

---

.github/workflows/publish.yml

This commit changes the publication action to use orphaned branches for the gh-pages commit / push. I.e. old gh-pages history gets deleted on push, which should lighten the repository when cloned.
Via https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan~
Closes #143

Publish: don't keep history in gh-pages branch

---

src/guide/agent-functions/agent-communication.rst
src/guide/host-functions/agent-operations.rst

Quick fix for variable name in the examples (t instead of sheep) and message type (MessageBruteForce where MessageBucket was to be used)

Fix variable name and message type

---

requirements.txt
src/conf.py.in
src/guide/agent-functions/agent-birth-death.rst
src/guide/agent-functions/index.rst
src/guide/creating-a-model/index.rst
src/guide/defining-execution-order/submodels.rst
src/guide/environment/index.rst
src/guide/host-functions/defining-host-functions.rst
src/guide/host-functions/index.rst
src/tutorial/index.rst

> Where do I place the setAgentOutput? Some hints would be nice. (Agent Functions::Agent Birth & Death::Enabling Agent Birth)
>The code snippets and the code summery do not fit together. Sometimes it is a model with 2 dimensions, sometimes one with 3 dimensions. (Tutorial)
> How is a HostFunction called / started by an agent? (Agent Functions or Hosts Function & Conditions)
> Move text about new FLAMEGPU2 functionality of environment macro properties to the Defining Macro Properties section. (Environmental Properties)
> What is a submodel and how is it used? Especially comparing with layers. (Defining Execution Order::Submodels)
> Some kind of overview or graphic how the different components like model, agents, functions, submodels and execution order interact with each other. (User …

Improvements suggested by Bytetec

---

src/guide/agent-functions/miscellaneous.rst

Add new `isAgent()`, `isState()` and missing `getID()`.
Relates: https://github.com/FLAMEGPU/FLAMEGPU2/pull/1116

Update DeviceAPI misc methods.

---

CMakeLists.txt
requirements.txt
src/conf.py.in
src/guide/agent-functions/agent-state-transitions.rst
src/guide/agent-functions/index.rst
src/guide/defining-agents/index.rst

Closes #169
~*May wish to rename `conditional-behaviours.rst` to `agent-state-transitions.rst`, however that will kill old links. @ptheywood has suggested there's Sphinx plugins to redirect old pages.*~

Expand agent state transition coverage.

---

.github/workflows/publish.yml

Switch to github pages deployment via custom action rather than the gh_pages branch.
Closes #61
This will require changes to https://github.com/FLAMEGPU/FLAMEGPU2-docs/settings/pages when merged to adjust where the gh pages content is sourced from, and ensure the cname value is still set to `docs.flamegpu.com`. 
The workflow may need manually re-invoking to trigger the deployment if the setting is not changed before the CI runs.
Manually tested on personal fork. Temporary demo: 
https://ptheywood.uk/FLAMEGPU2-docs/index.html
https://github.com/ptheywood/FLAMEGPU2-docs/actions/runs/6588199419

GH pages via actions/deploy-pages

---

.github/workflows/build.yml

*Unclear when this was introduced, I assume the default argument changed from `ON` to `OFF` but nothing obvious stands out from git blame.*
Closes #172
-------
`Build API 3.x` action now includes the compilation output `[  1%] Generate API documentation for api_docs_xml` and takes much longer with all the `writing output... [ 27%] api/define_HostAgentAPI_8cuh_1a64629b6c7aa246731d1657c3ad70996a` lines.
API artifacts are now [~40mb compared to 4mb](https://github.com/FLAMEGPU/FLAMEGPU2-docs/actions/runs/6875546919?pr=173), and downloading one showed the API pages present.

BugFix: CI was not building API docs

---

.github/workflows/publish.yml

Complements #173 and actually fixes the published cI build

Enable FLAMEGPU_BUILD_API_DOCUMENTATION in publish CI workflow

---

src/guide/running-multiple-simulations/index.rst

https://github.com/FLAMEGPU/FLAMEGPU2/pull/1152

Add RunPlanVector::setPropertyStep() example.
